version: '3'

services:
  dewey:
    environment:
      DEWEY_SECRET_KEY: "changeme"
      DEWEY_POSTGRES_HOST: "changeme"
      DEWEY_POSTGRES_PASSWORD: "changeme"

  dewey-celery-worker:
    environment:
      DEWEY_POSTGRES_HOST: "changeme"
      DEWEY_POSTGRES_PASSWORD: "changeme"

  dewey-celery-scheduler:
    environment:
      DEWEY_POSTGRES_HOST: "changeme"
      DEWEY_POSTGRES_PASSWORD: "changeme"

  dewey-celery-flower:
    environment:
      DEWEY_POSTGRES_HOST: "changeme"
      DEWEY_POSTGRES_PASSWORD: "changeme"
