# There are some extra steps required to start dewey the first time.
# These steps should be executed from the main dewey container
# - Populate the DB
#   - docker-compose run --rm -it --entrypoint /bin/sh dewey
#   - . /venvs/dewey/bin/activate
#   - dewey-manager migrate
#   - dewey-manager createsuperuser
#   - dewey-manager collectstatic
#   - exit
# - Start dewey
#   - docker-compose up

version: '3'

services:
  redis:
    image: redis:4.0.11-alpine

  dewey:
    image: plos/dewey:v0.0.20.2
    ports:
      - "8080:8080"
    depends_on:
      - redis

  dewey-celery-worker:
    image: plos/dewey:v0.0.20.2
    entrypoint: /code/bin/dewey-celery.sh
    command: worker
    depends_on:
      - dewey
      - redis

  dewey-celery-scheduler:
    image: plos/dewey:v0.0.20.2
    entrypoint: /code/bin/dewey-celery.sh
    command: beat
    depends_on:
      - dewey
      - redis

  dewey-celery-flower:
    image: plos/dewey:v0.0.20.2
    entrypoint: /code/bin/dewey-celery.sh
    command: flower
    ports:
      - "5555:5555"
    depends_on:
      - dewey
      - redis
